kind: ConfigMap
apiVersion: v1
metadata:
  name: db-init-sql
  namespace: example-app
data:
  init.sql: |-
    create table if not exists app_table (id int primary key, app_column text);
    insert into app_table (id, app_column) values (1, 'I am a MySQL DB row');
    insert into app_table (id, app_column) values (2, 'Whoohooo!');
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-app-db-persistent-volume-claim
  namespace: example-app
  labels:
    app: example-app-db
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: gp2    
---
apiVersion: v1
kind: Service
metadata:
  name: example-app-db
  namespace: example-app
  labels:
    app: example-app-db
spec:
  selector:
    app: example-app-db
  ports:
  - port: 3306
    targetPort: 3306
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: example-app-db
  namespace: example-app
  labels:
    app: example-app-db
spec:
  serviceName: example-app-db
  replicas: 1
  selector:
    matchLabels:
      app: example-app-db
  template:
    metadata:
      labels:
       app: example-app-db
    spec:
      containers:
      - name: example-app-db
        image: mysql:5
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: root_password
          - name: MYSQL_DATABASE
            value: app_database
          - name: MYSQL_USER
            value: app_user
          - name: MYSQL_PASSWORD
            value: app_password
        volumeMounts:
        - name: initdb-configmap
          mountPath: /docker-entrypoint-initdb.d
        - name: mysql-db-volume
          mountPath: /var/lib/mysql
          subPath: mysql
      volumes:
      - name: initdb-configmap
        configMap:
          name: db-init-sql
      - name: mysql-db-volume
        persistentVolumeClaim:
          claimName: example-app-db-persistent-volume-claim