---
apiVersion: v1
kind: Service
metadata:
  name: example-app-lb
  namespace: example-app
spec:
  selector:
    app: example-app
  type: NodePort
  ports:
  - name: example-app-port
    port: 3000
    targetPort: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-app-ingress
  namespace: example-app
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: ${DNS_NAME}
    http:
      paths:
      - path: /
        backend:
          serviceName: example-app-lb
          servicePort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app-deployment
  namespace: example-app
  labels:
    app: example-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: app
        image: ${CONTAINER_REGISTRY}/example-app
        imagePullPolicy: Always
        env:
        - name: DB_HOST
          value: example-app-db
        - name: DB_USER
          value: app_user
        - name: DB_PASSWORD
          value: app_password
        - name: DB_DRIVER
          value: mysql
        ports:
        - name: app-port
          containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: app-port
      imagePullSecrets:
      - name: acr-auth