---
apiVersion: v1
kind: Service
metadata:
  name: example-app-lb
spec:
  selector:
    app: example-app
  type: NodePort
  ports:
  - port: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: example-app-lb
          servicePort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app-deployment
  labels:
    app: example-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: example-app
  template:
      metadata:
         labels:
           app: example-app
      spec:
          containers:
          - name: app
            image: example-app
            imagePullPolicy: Never
            env:
              - name: DB_HOST
                value: example-app-db
              - name: DB_USER
                value: app_user
              - name: DB_PASSWORD
                value: app_password
              - name: DB_DRIVER
                value: mysql
            ports:
            - containerPort: 3000
