apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-app-db-persistent-volume-claim
  labels:
    app: example-app-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

