apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: example-app-db
  labels:
    app: example-app-db
spec:
  serviceName: example-app-db
  replicas: 1
  selector:
    matchLabels:
      app: example-app-db
  template:
    metadata:
      labels:
        app: example-app-db
    spec:
      containers:
        - name: example-app-db
          image: mysql:5
          imagePullPolicy: Always
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root_password
            - name: MYSQL_DATABASE
              value: app_database
            - name: MYSQL_USER
              value: app_user
            - name: MYSQL_PASSWORD
              value: app_password
          volumeMounts:
            - name: initdb-configmap
              mountPath: /docker-entrypoint-initdb.d
            - name: mysql-db-volume
              mountPath: /var/lib/mysql
              subPath: mysql
      volumes:
        - name: initdb-configmap
          configMap:
            name: db-init-sql
        - name: mysql-db-volume
          persistentVolumeClaim:
            claimName: example-app-db-persistent-volume-claim