version: "3"

services:
  app:
      image: example-app
      environment:
        DB_HOST: app_db
        DB_USER: app_user
        DB_PASSWORD: app_password
        DB_DRIVER: mysql
      ports:
        - "3000:3000"

  app_db:
      image: mysql:5
      environment:
        MYSQL_ROOT_PASSWORD: root_password
        MYSQL_DATABASE: app_database
        MYSQL_USER:  app_user
        MYSQL_PASSWORD: app_password
      expose:
        - "3306"
