apiVersion: v1
kind: Service
metadata:
  name: example-app-lb
spec:
  selector:
    app: example-app
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app-deployment
  labels:
    app: example-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: example-app
  template:
      metadata:
         labels:
           app: example-app
      spec:
          containers:
          - name: app
            image: us.gcr.io/${DOCKER_REGISTRY_NAMESPACE}/example-app
            env:
              - name: DB_HOST
                value: localhost
              - name: DB_USER
                value: app_user
              - name: DB_PASSWORD
                value: app_password
              - name: DB_DRIVER
                value: mysql
            ports:
            - containerPort: 3000
          - name: app-db
            image: mysql:5
            imagePullPolicy: Always
            ports:
            - containerPort: 3306
            env:
              - name: MYSQL_ROOT_PASSWORD
                value: root_password
              - name: MYSQL_DATABASE
                value: app_database
              - name: MYSQL_USER
                value: app_user
              - name: MYSQL_PASSWORD
                value: app_password
